name: Build and push container image to GHCR

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Fetch repository source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Convert owner name to lowercase because GHCR requires lowercase image paths
      - name: Set lowercase owner
        run: echo "OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Define SHA_TAG: short commit hash for traceable builds
      - name: Set SHA tag
        run: |
          echo "SHA_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # Authenticate to GitHub Container Registry using PAT stored in secrets
      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build container image and attach tags:
      # - latest: always points to newest build
      # - SHA tag: specific commit version
      # - uses local layer cache if available (Podman default behavior)
      - name: Build image
        run: |
           podman build \
            --layers \
            -t ghcr.io/${{ env.OWNER_LC }}/myapp:latest \
            -t ghcr.io/${{ env.OWNER_LC }}/myapp:${{ env.SHA_TAG }} \
            .
      # Push tags to registry
      - name: Push latest image
        run: |
          podman push ghcr.io/${{ env.OWNER_LC }}/myapp:latest
          podman push ghcr.io/${{ env.OWNER_LC }}/myapp:${{ env.SHA_TAG }}
